"""changed_movements_fields

Revision ID: 5dfaf7077b37
Revises: b4ba72ed2038
Create Date: 2025-09-24 22:49:21.081323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dfaf7077b37'
down_revision: Union[str, Sequence[str], None] = 'b4ba72ed2038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('movement_date', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'movements', ['id'])
    op.drop_column('movements', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movements', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'movements', type_='unique')
    op.drop_column('movements', 'movement_date')
    # ### end Alembic commands ###
