"""changed_partners_fields

Revision ID: fc7b5e4cea72
Revises: 5dfaf7077b37
Create Date: 2025-09-25 06:56:35.032283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc7b5e4cea72'
down_revision: Union[str, Sequence[str], None] = '5dfaf7077b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partners', sa.Column('code', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'partners', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'partners', type_='unique')
    op.drop_column('partners', 'code')
    # ### end Alembic commands ###
